name: CI - Retrain Model

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas numpy scikit-learn joblib

      - name: Run MLflow Project
        working-directory: ./MLProject
        run: |
          mlflow run . --env-manager=local -P n_estimators=200 -P max_depth=8

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-model-artifacts
          path: |
            MLProject/mlruns/
            MLProject/*.png
            MLProject/*.txt
            MLProject/*.joblib
          retention-days: 7
          if-no-files-found: ignore