name: CI - Retrain Model

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas numpy scikit-learn joblib

      - name: Run MLflow Project
        working-directory: ./MLProject
        env:
          MLFLOW_TRACKING_URI: sqlite:///mlflow.db
        run: |
          mlflow run . --env-manager=local -P n_estimators=200 -P max_depth=8

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-model-artifacts
          path: |
            MLProject/mlruns/
            MLProject/mlflow.db
            MLProject/run_id.txt
            MLProject/*.png
            MLProject/*.txt
            MLProject/*.joblib
          retention-days: 7
          if-no-files-found: ignore

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image with MLflow
        if: github.event_name != 'pull_request'
        working-directory: ./MLProject
        env:
          MLFLOW_TRACKING_URI: sqlite:///mlflow.db
        run: |
          RUN_ID=$(cat run_id.txt)
          echo "MLflow Run ID: $RUN_ID"
          mlflow models build-docker \
            --model-uri "runs:/$RUN_ID/model" \
            --name "raynaldi/telco-churn-mlflow:latest" \
            --env-manager=local

      - name: Push Docker image to Docker Hub
        if: github.event_name != 'pull_request'
        run: |
          docker push raynaldi/telco-churn-mlflow:latest